### ISSUE TITLE
Feature: configure datapath for networkservice via defined forwarder interface

### ISSUE THREAD

**Issue by barby1138** [networkservicemesh/deployments-k8s#10024]
Hi guys
Another feature is missing for me is subj
My vision for implementation:
Example:

we have ability to configure selector in forwarder:
for node/cluster1

```
---
interfaces:
  - name: int1
    matches:
       - labelSelector:
           - via: gw1
```

for node/cluster2

```
---
interfaces:
  - name: int2
    matches:
       - labelSelector:
           - via: gw1
```

And Im aware that int1 coonected to int2 via router.
So I want data path to be routed via those interfaces. So...

for networkservice declaration I want to add gw_selector field:

Example:

```
apiVersion: networkservicemesh.io/v1
kind: NetworkService
metadata:
  name: registry-local-endpoint
spec:
  payload: ETHERNET

  matches:
  - routes:
    - destination_selector:
        app: nse-1
    source_selector: null
    gw_selector: gw1
```

What do you think?
Thank you!!!
Have a nice day!!!
