### ISSUE TITLE
About nse-composition example config develop

### ISSUE THREAD

**Issue by 316953425** [networkservicemesh/deployments-k8s#10319]
Hi
I deploy nse-composition example followd：https://github.com/networkservicemesh/deployments-k8s/tree/v1.6.1/examples/features/nse-composition

I do not understand nse-composition-ns.yaml 
1、What is the difference between payload: ETHERNET and payload: IP?
2、How source_selector and routes handle data packets sent by nsc？
3、if nsc send icmp package， the icmp package how to forwarded  according  to nse-composition-ns.yaml ？
Is it transmitted like this nsc -> firewall -> passthrough-1 -> passthrough-2 -> passthrough-3 ->gateway?

When i create another nsc use file as followed:
```
---
apiVersion: v1
kind: Pod
metadata:
  name: alpine2
  labels:
    app: alpine2
  annotations:
    networkservicemesh.io: kernel://nse-composition/nsm-2
spec:
  containers:
  - name: alpine
    image: alpine:3.15.0
    imagePullPolicy: IfNotPresent
    stdin: true
    tty: true
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - topologyKey: kubernetes.io/hostname
          labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - nse-kernel
```
this pod alpine2 only can ping nse, Both wget 8080 and wget 80 can not access 
Could you tell me why?
thanks very much

**Comment by 316953425** [comment]
Who can help me answer this, thank you very much

**Comment by 316953425** [comment]
This is can work ,close it

**Comment by glazychev-art** [comment]
Hello @316953425 ,
1. If your client work at the L2 level, then you need to use `payload:Ethernet`. If on L3 (operates with IP packets), then `payload:IP`. Depending on this, different types of interfaces will appear on your client - like TUN/TAP in Linux.
2. Actually NSM has a Control plane (CP) and a Data plane (DP). The Control plane (uses gRPC) makes sure that the Data plane is created and your data can reach the endpoint (many of our examples use VPP for that).
The `source_selector` is related to CP. Using labels, it allows you to build the correct chain of applications. `source_selector` checks for an occurrence of the specified client label. If the label is found, then the corresponding `route` is used - https://networkservicemesh.io/docs/concepts/architecture/#network-service
For example, in the nse-composition example the [client doesn't have any labels](https://github.com/networkservicemesh/deployments-k8s/blob/v1.6.1/examples/features/nse-composition/client.yaml#L9), so the `firewall` will be used.
Firewall then [adds it's own labes](https://github.com/networkservicemesh/deployments-k8s/blob/v1.6.1/examples/features/nse-composition/nse-firewall/patch-nse-firewall-vpp.yaml#L14-L15C34). So `passthrough-1` will be selected afterwards and so on.

3. Yes, you are right. This list comes from the previous point

4. Your alpine2.yaml is absolutely correct. But, unfortunately, we found a bug in the firewall. The PR has already been prepared, we will fix it soon. Thanks!

**Comment by 316953425** [comment]
> Hello @316953425 ,
> 
> 1. If your client works on the L2 level, then you need to use `payload:Ethernet`. If on L3 (operates with IP packets), then `payload:IP`. Depending on this, different types of interfaces will appear on your client - like TUN/TAP in Linux.
> 2. Actually NSM has a Control plane (CP) and a Data plane (DP). The Control plane (uses gRPC) makes sure that the Data plane is created and your data can reach the endpoint (many of our examples use VPP for that).
>    The `source_selector` is related to CP. Using labels, it allows you to build the correct chain of applications. `source_selector` checks for an occurrence of the specified client label. If the label is found, then the corresponding `route` is used - https://networkservicemesh.io/docs/concepts/architecture/#network-service
>    For example, in the nse-composition example the [client doesn't have any labels](https://github.com/networkservicemesh/deployments-k8s/blob/v1.6.1/examples/features/nse-composition/client.yaml#L9), so the `firewall` will be used.
>    Firewall then [adds it's own labes](https://github.com/networkservicemesh/deployments-k8s/blob/v1.6.1/examples/features/nse-composition/nse-firewall/patch-nse-firewall-vpp.yaml#L14-L15C34). So `passthrough-1` will be selected afterwards and so on.
> 3. Yes, you are right. This list comes from the previous point
> 4. Your alpine2.yaml is absolutely correct. But, unfortunately, we found a bug in the firewall. The PR has already been prepared, we will fix it soon. Thanks!

Hi @glazychev-art ,
If I want to replace the vpp-based image of nse-firewall with a Linux kernel-based image, and then use iptables to filter packets, how can I achieve this? Can you provide me with a simple example? Thank you very much.

**Comment by 316953425** [comment]
> > Hello @316953425 ,
> > 
> > 1. If your client works on the L2 level, then you need to use `payload:Ethernet`. If on L3 (operates with IP packets), then `payload:IP`. Depending on this, different types of interfaces will appear on your client - like TUN/TAP in Linux.
> > 2. Actually NSM has a Control plane (CP) and a Data plane (DP). The Control plane (uses gRPC) makes sure that the Data plane is created and your data can reach the endpoint (many of our examples use VPP for that).
> >    The `source_selector` is related to CP. Using labels, it allows you to build the correct chain of applications. `source_selector` checks for an occurrence of the specified client label. If the label is found, then the corresponding `route` is used - https://networkservicemesh.io/docs/concepts/architecture/#network-service
> >    For example, in the nse-composition example the [client doesn't have any labels](https://github.com/networkservicemesh/deployments-k8s/blob/v1.6.1/examples/features/nse-composition/client.yaml#L9), so the `firewall` will be used.
> >    Firewall then [adds it's own labes](https://github.com/networkservicemesh/deployments-k8s/blob/v1.6.1/examples/features/nse-composition/nse-firewall/patch-nse-firewall-vpp.yaml#L14-L15C34). So `passthrough-1` will be selected afterwards and so on.
> > 3. Yes, you are right. This list comes from the previous point
> > 4. Your alpine2.yaml is absolutely correct. But, unfortunately, we found a bug in the firewall. The PR has already been prepared, we will fix it soon. Thanks!
> 
> Hi @glazychev-art , If I want to replace the vpp-based image of nse-firewall with a Linux kernel-based image, and then use iptables to filter packets, how can I achieve this? Can you provide me with a simple example? Thank you very much.

**Comment by glazychev-art** [comment]
At the moment there is no solution out of the box. But not so long ago we were solved a similar problem. Could you please take a look if this is what you need?
https://github.com/networkservicemesh/deployments-k8s/issues/9676
https://github.com/networkservicemesh/deployments-k8s/issues/9864

**Comment by glazychev-art** [comment]
@denis-tingaikin, @edwarnicke 
It looks like we need forwarder-kernel functionality

**Comment by 316953425** [comment]
> At the moment there is no solution out of the box. But not so long ago we were solving a similar problem. Could you please take a look if this is what you need? #9676 #9864

hi @glazychev-art 
i use https://github.com/networkservicemesh/deployments-k8s/files/12664791/nse-kernel-composition.zip in https://github.com/networkservicemesh/deployments-k8s/issues/9864
but alpine can not start

**Comment by 316953425** [comment]
hi @glazychev-art 
Has this bug in the firewall been fixed? If it has been fixed, I hope you can tell it where it is and how to use it. Thank you very much.
> 4. Your alpine2.yaml is absolutely correct. But, unfortunately, we found a bug in the firewall. The PR has already been prepared, we will fix it soon. Thanks!

**Comment by glazychev-art** [comment]
Yes. Please try this image for the firewall:
`ghcr.io/networkservicemesh/ci/cmd-nse-firewall-vpp:42eae22`

**Comment by 316953425** [comment]
> Yes. Please try this image for the firewall: `ghcr.io/networkservicemesh/ci/cmd-nse-firewall-vpp:42eae22`

hi @glazychev-art 
Your efficient work has helped me a lot, thank you very much

**Comment by 316953425** [comment]
> Yes. Please try this image for the firewall: `ghcr.io/networkservicemesh/ci/cmd-nse-firewall-vpp:42eae22`

hi @glazychev-art 
Does nse-composition now support dual stack?
thanks

**Comment by glazychev-art** [comment]
Yes it does

**Comment by 316953425** [comment]
> Yes it does
hi @glazychev-art 
in nse-composition example
how to add icmpv6 allow in firewall config firewall-config-file
i add like this 

```
    allow icmpv6:
      ispermit: 1
      proto: 1
      srcportoricmptypelast: 65535
      dstportoricmpcodelast: 65535
```

But it doesn't seem right. Can you tell me the correct way? Thank you very much.

**Comment by glazychev-art** [comment]
ICMPv6 is 58 IP-protocol - https://www.iana.org/assignments/protocol-numbers/protocol-numbers.xhtml

Please try this:
```
    allow icmpv6:
      ispermit: 1
      proto: 58
      srcprefix: ::/0
      dstprefix: ::/0
      srcportoricmptypelast: 65535
      dstportoricmpcodelast: 65535
```

**Comment by 316953425** [comment]
hi @glazychev-art 

for ipv6, this config as followed didn’t take effect. There is an error there. Could you help me take a look. Thanks again.

```
    allow tcp8080:
      ispermit: 1
      is_ipv6: 1
      proto: 6
      srcportoricmptypelast: 65535
      dstportoricmpcodefirst: 8080
      dstportoricmpcodelast: 8080
    forbid tcp80:
      proto: 6
      is_ipv6: 1
      srcportoricmptypelast: 65535
      dstportoricmpcodefirst: 80
      dstportoricmpcodelast: 80
```

**Comment by glazychev-art** [comment]
Please try this:
```
    allow tcp8080v6:
      ispermit: 1
      proto: 6
      srcprefix: ::/0
      dstprefix: ::/0
      srcportoricmptypelast: 65535
      dstportoricmpcodefirst: 8080
      dstportoricmpcodelast: 8080
    forbid tcp80v6:
      proto: 6
      srcprefix: ::/0
      dstprefix: ::/0
      srcportoricmptypelast: 65535
      dstportoricmpcodefirst: 80
      dstportoricmpcodelast: 80
```

**Comment by 316953425** [comment]
hi @glazychev-art 
I use the new image you provided ghcr.io/networkservicemesh/ci/cmd-nse-firewall-vpp:42eae22. Most time are fine, but sometimes I find that alpine does not actually have an nsm-1 interface, but alpine can normally start
![image](https://github.com/networkservicemesh/deployments-k8s/assets/3714619/b2ce2fbd-64d3-4f48-9b5d-e7a7aa95b8cb)


conifig:
[nse-composition.zip](https://github.com/networkservicemesh/deployments-k8s/files/13739682/nse-composition.zip)

**Comment by glazychev-art** [comment]
Are you using v1.11.1?
How long after deployment does the problem happen?

**Comment by 316953425** [comment]
> Are you using v1.11.1? How long after deployment does the problem happen?
hi @glazychev-art 
>Are you using v1.11.1?

yes

>How long after deployment does the problem happen?

Sometimes it appears immediately after deployment, and sometimes it takes a while, but it appears more often immediately after deployment.

**Comment by glazychev-art** [comment]
Got it, thanks. I'll take a look

If you have a chance, could you please send NSM logs after the problem happens?
1. Set the [following env](https://github.com/networkservicemesh/deployments-k8s/blob/v1.11.1/apps/admission-webhook-k8s/admission-webhook.yaml#L48-L49) for the admission-webhook:
```
            - name: NSM_ENVS
              value: NSM_LOG_LEVEL=TRACE
```
2. Please change the log level from `INFO` to `TRACE` for NSM components:
https://github.com/networkservicemesh/deployments-k8s/blob/v1.11.1/apps/nsmgr/nsmgr.yaml#L33-L34
https://github.com/networkservicemesh/deployments-k8s/blob/v1.11.1/apps/forwarder-vpp/forwarder.yaml#L30-L31
https://github.com/networkservicemesh/deployments-k8s/blob/v1.11.1/apps/nse-kernel/nse.yaml#L31-L32
3. Please attach the cluster-info
```
kubectl cluster-info dump -n nsm-system --output-directory nsm-dump
kubectl cluster-info dump -n ns-nse-composition --output-directory nsm-dump
```

**Comment by 316953425** [comment]
hi @glazychev-art 
Once it reproduces, I will immediately share the relevant debug information, thank you

**Comment by 316953425** [comment]
hi @glazychev-art 

kubectl cluster-info dump -n nsm-system --output-directory nsm-dump
[nsm-dump.zip](https://github.com/networkservicemesh/deployments-k8s/files/13768969/nsm-dump.zip)

**Comment by glazychev-art** [comment]
Thank you very much, I'll take a look
Another question:
Could you also please set the [following envs](https://github.com/networkservicemesh/deployments-k8s/blob/v1.11.1/apps/admission-webhook-k8s/admission-webhook.yaml#L48-L49) for the admission-webhook:
```
            - name: NSM_ENVS
              value: NSM_LOG_LEVEL=TRACE,NSM_LIVENESSCHECKENABLED=false
```

Redeploy NSM, and share the output of ping commands from clients for IPv4 and IPv6?

**Comment by 316953425** [comment]
hi @glazychev-art 
Everything seems to be working fine

>            - name: NSM_ENVS
              value: NSM_LOG_LEVEL=TRACE,NSM_LIVENESSCHECKENABLED=false

<img width="646" alt="1703637039897" src="https://github.com/networkservicemesh/deployments-k8s/assets/3714619/5a02c1b5-1841-42f4-b586-237a41740a64">

**Comment by 316953425** [comment]
> Are you using v1.11.1? How long after deployment does the problem happen?

hi @glazychev-art 
The disappearance of nsm-1 appears 
<img width="716" alt="1703661053362" src="https://github.com/networkservicemesh/deployments-k8s/assets/3714619/743d400a-9f0c-41aa-a890-9ff8e2abe5e1">
<img width="701" alt="1703661075187" src="https://github.com/networkservicemesh/deployments-k8s/assets/3714619/37c8c56b-2fc1-40a6-9021-c1a3ede26c83">
<img width="673" alt="1703661096485" src="https://github.com/networkservicemesh/deployments-k8s/assets/3714619/dc6ac124-008f-4bf4-8920-46fb5e429c53">

 kubectl cluster-info dump -n nsm-system --output-directory nsm-dump
[nsm-dump.zip](https://github.com/networkservicemesh/deployments-k8s/files/13776395/nsm-dump.zip)

**Comment by glazychev-art** [comment]
Thanks,
It looks like forwarder was killed by OOM.
Question, how much memory do your servers have?

**Comment by 316953425** [comment]
> Thanks, It looks like forwarder was killed by OOM. Question, how much memory do your servers have?

hi @glazychev-art 
in my node memory is as followed:

```
[root@CNCP-MS-01 ~]# free -g
              total        used        free      shared  buff/cache   available
Mem:            125          14          93           0          17         109
Swap:             0           0           0

```

forward memory i not change 


```
[root@CNCP-MS-01 deployments-k8s-release-v1.11.1]# cat apps/forwarder-vpp/forwarder.yaml
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: forwarder-vpp
  labels:
    app: forwarder-vpp
spec:
  selector:
    matchLabels:
      app: forwarder-vpp
  template:
    metadata:
      labels:
        app: forwarder-vpp
        "spiffe.io/spiffe-id": "true"
    spec:
      hostPID: true
      #hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        #- image: ghcr.io/networkservicemesh/cmd-forwarder-vpp:v1.11.1
        - image: artgl/cmd-forwarder-vpp:cilium_test
          imagePullPolicy: IfNotPresent
          name: forwarder-vpp
          securityContext:
            privileged: true
          env:
            - name: SPIFFE_ENDPOINT_SOCKET
              value: unix:///run/spire/sockets/agent.sock
            - name: NSM_LOG_LEVEL
              #value: INFO
              value: TRACE
            - name: NSM_CONNECT_TO
              value: unix:///var/lib/networkservicemesh/nsm.io.sock
            - name: NSM_LISTEN_ON
              value: unix:///listen.on.sock
            - name: NSM_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          volumeMounts:
            - name: spire-agent-socket
              mountPath: /run/spire/sockets
              readOnly: true
            - name: nsm-socket
              mountPath: /var/lib/networkservicemesh
            - name: kubelet-socket
              mountPath: /var/lib/kubelet
            - name: cgroup
              mountPath: /host/sys/fs/cgroup
            - name: vfio
              mountPath: /host/dev/vfio
            - name: vpp
              mountPath: /var/run/vpp/external
          resources:
            requests:
              memory: 350Mi
              cpu: 150m
            limits:
              memory: 500Mi
              cpu: 525m
          readinessProbe:
            exec:
              command: ["/bin/grpc-health-probe", "-spiffe", "-addr=unix:///listen.on.sock"]
            failureThreshold: 120
            initialDelaySeconds: 1
            periodSeconds: 1
            successThreshold: 1
            timeoutSeconds: 2
          livenessProbe:
            exec:
              command: ["/bin/grpc-health-probe", "-spiffe", "-addr=unix:///listen.on.sock"]
            failureThreshold: 25
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 2
          startupProbe:
            exec:
              command: ["/bin/grpc-health-probe", "-spiffe", "-addr=unix:///listen.on.sock"]
            failureThreshold: 25
            periodSeconds: 5
      volumes:
        - name: spire-agent-socket
          hostPath:
            path: /run/spire/sockets
            type: Directory
        - name: nsm-socket
          hostPath:
            path: /var/lib/networkservicemesh
            type: DirectoryOrCreate
        - name: kubelet-socket
          hostPath:
            path: /var/lib/kubelet
            type: Directory
        - name: cgroup
          hostPath:
            path: /sys/fs/cgroup
            type: Directory
        - name: vfio
          hostPath:
            path: /dev/vfio
            type: DirectoryOrCreate
        - name: vpp
          hostPath:
            path: /var/run/vpp
            type: DirectoryOrCreate
```
