### ISSUE TITLE
network service endpoint candidates not found: all forwarders have failed

### ISSUE THREAD

**Issue by 316953425** [networkservicemesh/deployments-k8s#10378]
I deploy the example https://github.com/networkservicemesh/deployments-k8s/tree/v1.6.1/examples/use-cases/Kernel2Wireguard2Kernel first, and it work well
But when i deploy anther case like as followd:

client.yaml

```
---
apiVersion: v1
kind: Pod
metadata:
  name: alpine2
  labels:
    app: alpine2
  annotations:
    networkservicemesh.io: kernel://x2kernel2wireguard2kernel/nsm-21
spec:
  containers:
  - name: alpine2
    #image: alpine:3.15.0
    image: nelson/ubuntu:16.04
    imagePullPolicy: IfNotPresent
    stdin: true
    tty: true
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - topologyKey: kubernetes.io/hostname
          labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - nse-kernel2
```

netsvc.yaml:

---
```
apiVersion: networkservicemesh.io/v1
kind: NetworkService
metadata:
  name: x2kernel2wireguard2kernel
  namespace: nsm-system
spec:
  payload: IP
```
kustomization.yaml:

```
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ns-2kernel2wireguard2kernel

bases:
- ../../../apps/2nse-kernel

resources:
- client.yaml
- netsvc.yaml

patchesStrategicMerge:
- patch-nse.yaml
```

patch-nse.yaml:

```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nse-kernel2
spec:
  template:
    spec:
      containers:
        - name: nse2
          env:
            - name: NSM_CIDR_PREFIX
              value: 10.188.1.1/16
            - name: NSM_PAYLOAD
              value: IP
            - name: NSM_SERVICE_NAMES
              value: "x2kernel2wireguard2kernel"
            - name: NSM_REGISTER_SERVICE
              value: "false"
```
../../../apps/2nse-kernel/nse.yaml:

```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nse-kernel2
  labels:
    app: nse-kernel2
  annotations:
    networkservicemesh.io: kernel://kernel2wireguard2kernel/nsm-2to1 

spec:
  selector:
    matchLabels:
      app: nse-kernel2
  template:
    metadata:
      labels:
        app: nse-kernel2
        "spiffe.io/spiffe-id": "true"
    spec:
      containers:
        - name: nse2
          image: ghcr.io/networkservicemesh/cmd-nse-icmp-responder:v1.6.1
          imagePullPolicy: IfNotPresent
          env:
            - name: SPIFFE_ENDPOINT_SOCKET
              value: unix:///run/spire/sockets/agent.sock
            - name: NSM_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NSM_LOG_LEVEL
              value: TRACE
            - name: NSM_CONNECT_TO
              value: unix:///var/lib/networkservicemesh/nsm.io.sock
          volumeMounts:
            - name: spire-agent-socket2
              mountPath: /run/spire/sockets
              readOnly: true
            - name: nsm-socket2
              mountPath: /var/lib/networkservicemesh
              readOnly: true
          resources:
            requests:
              cpu: 100m
              memory: 40Mi
            limits:
              memory: 80Mi
              cpu: 200m
      volumes:
        - name: spire-agent-socket2
          hostPath:
            path: /run/spire/sockets
            type: Directory
        - name: nsm-socket2
          hostPath:
            path: /var/lib/networkservicemesh
            type: DirectoryOrCreate
```

When the nse-kernel2 pod start , interface nsm-2to1 is configed ip is already used in the nsc deployed in Kernel2Wireguard2Kernel
And sometime ,the nsc in x2kernel2wireguard2kernel can not start ,
errlog is as followed:

`Nov  9 11:35:03.531 [ERRO] [id:alpine2-0] [type:networkService] (2.1)    Error returned from api/pkg/api/networkservice/networkServiceClient.Request: rpc error: code = Unknown desc = 0. An error during select forwawrder forwarder-vpp-fgbk9 --> Error returned from sdk/pkg/networkservice/common/connect/connectClient.Request: rpc error: code = Unknown desc = network service endpoint candidates not found: all forwarders have failed: cannot support any of the requested mechanism`

Could you tell me why, and how to fixed it?
thanks

**Comment by 316953425** [comment]
> I deploy the example https://github.com/networkservicemesh/deployments-k8s/tree/v1.6.1/examples/use-cases/Kernel2Wireguard2Kernel first, and it work well But when i deploy anther case like as followd:
> 
> client.yaml
> 
> ```
> ---
> apiVersion: v1
> kind: Pod
> metadata:
>   name: alpine2
>   labels:
>     app: alpine2
>   annotations:
>     networkservicemesh.io: kernel://2xkernel2wireguard2kernel/nsm-21
> spec:
>   containers:
>   - name: alpine2
>     #image: alpine:3.15.0
>     image: nelson/ubuntu:16.04
>     imagePullPolicy: IfNotPresent
>     stdin: true
>     tty: true
>   affinity:
>     podAntiAffinity:
>       requiredDuringSchedulingIgnoredDuringExecution:
>         - topologyKey: kubernetes.io/hostname
>           labelSelector:
>             matchExpressions:
>               - key: app
>                 operator: In
>                 values:
>                   - nse-kernel2
> ```
> 
> netsvc.yaml:
> 
> ```
> apiVersion: networkservicemesh.io/v1
> kind: NetworkService
> metadata:
>   name: x2kernel2wireguard2kernel
>   namespace: nsm-system
> spec:
>   payload: IP
> ```
> 
> kustomization.yaml:
> 
> ```
> ---
> apiVersion: kustomize.config.k8s.io/v1beta1
> kind: Kustomization
> 
> namespace: ns-2kernel2wireguard2kernel
> 
> bases:
> - ../../../apps/2nse-kernel
> 
> resources:
> - client.yaml
> - netsvc.yaml
> 
> patchesStrategicMerge:
> - patch-nse.yaml
> ```
> 
> patch-nse.yaml:
> 
> ```
> ---
> apiVersion: apps/v1
> kind: Deployment
> metadata:
>   name: nse-kernel2
> spec:
>   template:
>     spec:
>       containers:
>         - name: nse2
>           env:
>             - name: NSM_CIDR_PREFIX
>               value: 10.188.1.1/16
>             - name: NSM_PAYLOAD
>               value: IP
>             - name: NSM_SERVICE_NAMES
>               value: "x2kernel2wireguard2kernel"
>             - name: NSM_REGISTER_SERVICE
>               value: "false"
> ```
> 
> ../../../apps/2nse-kernel/nse.yaml:
> 
> ```
> ---
> apiVersion: apps/v1
> kind: Deployment
> metadata:
>   name: nse-kernel2
>   labels:
>     app: nse-kernel2
>   annotations:
>     networkservicemesh.io: kernel://kernel2wireguard2kernel/nsm-2to1 
> 
> spec:
>   selector:
>     matchLabels:
>       app: nse-kernel2
>   template:
>     metadata:
>       labels:
>         app: nse-kernel2
>         "spiffe.io/spiffe-id": "true"
>     spec:
>       containers:
>         - name: nse2
>           image: ghcr.io/networkservicemesh/cmd-nse-icmp-responder:v1.6.1
>           imagePullPolicy: IfNotPresent
>           env:
>             - name: SPIFFE_ENDPOINT_SOCKET
>               value: unix:///run/spire/sockets/agent.sock
>             - name: NSM_NAME
>               valueFrom:
>                 fieldRef:
>                   fieldPath: metadata.name
>             - name: NSM_LOG_LEVEL
>               value: TRACE
>             - name: NSM_CONNECT_TO
>               value: unix:///var/lib/networkservicemesh/nsm.io.sock
>           volumeMounts:
>             - name: spire-agent-socket2
>               mountPath: /run/spire/sockets
>               readOnly: true
>             - name: nsm-socket2
>               mountPath: /var/lib/networkservicemesh
>               readOnly: true
>           resources:
>             requests:
>               cpu: 100m
>               memory: 40Mi
>             limits:
>               memory: 80Mi
>               cpu: 200m
>       volumes:
>         - name: spire-agent-socket2
>           hostPath:
>             path: /run/spire/sockets
>             type: Directory
>         - name: nsm-socket2
>           hostPath:
>             path: /var/lib/networkservicemesh
>             type: DirectoryOrCreate
> ```
> 
> When the nse-kernel2 pod start , interface nsm-2to1 is configed ip is already used in the nsc deployed in Kernel2Wireguard2Kernel And sometime ,the nsc in x2kernel2wireguard2kernel can not start , errlog is as followed:
> 
> `Nov 9 11:35:03.531 [ERRO] [id:alpine2-0] [type:networkService] (2.1) Error returned from api/pkg/api/networkservice/networkServiceClient.Request: rpc error: code = Unknown desc = 0. An error during select forwawrder forwarder-vpp-fgbk9 --> Error returned from sdk/pkg/networkservice/common/connect/connectClient.Request: rpc error: code = Unknown desc = network service endpoint candidates not found: all forwarders have failed: cannot support any of the requested mechanism`
> 
> Could you tell me why, and how to fixed it? thanks

**Comment by 316953425** [comment]
> Hello @316953425 .
> 
> As I can see your network service is x2kernel2wireguard2kernel When you're using this network service in the client kernel://2xkernel2wireguard2kernel/nsm-21
> 
> I feel it could resolve the problem.
> 
> ```diff
> +++  kernel://x2kernel2wireguard2kernel
> ---  kernel://2xkernel2wireguard2kernel
> ```

Hi,denis-tingaikin
thanks for you reply
I accidentally wrote it wrong，In fact, x2kernel2wireguard2kernel is used, but the problem still exists

**Comment by NikitaSkrynnik** [comment]
Hello @316953425 
`NSM_REGISTER_SERVICE=true` tells the NSE to register Network Service`x2kernel2wireguard2kernel`. It is set to `false` because we don't want the NSE to register this Network Service. We add it manually in `kustomization.yaml` file. The file with Network Service specification is called `netsvc.yaml` usually.

**Comment by 316953425** [comment]
> Hello @316953425 `NSM_REGISTER_SERVICE=true` tells the NSE to register Network Service`x2kernel2wireguard2kernel`. It is set to `false` because we don't want the NSE to register this Network Service. We add the service manually in `kustomization.yaml` file. The file with Network Service specification is called `netsvc.yaml` usually.
Hi,
nsc1.yaml 
```
---
apiVersion: v1
kind: Pod
metadata:
  name: alpine2
  labels:
    app: alpine2
  annotations:
    networkservicemesh.io: kernel://x2kernel2wireguard2kernel/nsm-21
spec:
  containers:
  - name: alpine2
    #image: alpine:3.15.0
    image: nelson/ubuntu:16.04
    imagePullPolicy: IfNotPresent
    stdin: true
    tty: true
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - topologyKey: kubernetes.io/hostname
          labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - nse-kernel2
```

nsc2.yaml
---
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nsc-kernel
  labels:
    app: nsc-kernel
spec:
  selector:
    matchLabels:
      app: nsc-kernel
  template:
    metadata:
      labels:
        app: nsc-kernel
        "spiffe.io/spiffe-id": "true"
    spec:
      containers:
        - name: nsc

          image: cmd-nsc
          imagePullPolicy: IfNotPresent
          env:
            - name: NSM_NETWORK_SERVICES
              value: kernel://test/nsm-1

            - name: SPIFFE_ENDPOINT_SOCKET
              value: unix:///run/spire/sockets/agent.sock
            - name: NSM_LOG_LEVEL
              value: TRACE
            - name: NSM_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          volumeMounts:
            - name: spire-agent-socket
              mountPath: /run/spire/sockets
              readOnly: true
            - name: nsm-socket
              mountPath: /var/lib/networkservicemesh
              readOnly: true
          resources:
            requests:
              cpu: 100m
              memory: 40Mi
            limits:
              memory: 80Mi
              cpu: 200m
      volumes:
        - name: spire-agent-socket
          hostPath:
            path: /run/spire/sockets
            type: Directory
        - name: nsm-socket
          hostPath:
            path: /var/lib/networkservicemesh
            type: DirectoryOrCreate
```
What is the difference between nsc1.yaml and nsc2.yaml? I see that some places use something similar to nsc1.yaml, but some places use something similar to nsc2.yaml.

Thank you so much
