### ISSUE TITLE
About vl3-basic example high latency

### ISSUE THREAD

**Issue by 316953425** [networkservicemesh/deployments-k8s#10488]
I deploy the vl3-basic as followed ：
https://github.com/networkservicemesh/deployments-k8s/tree/release/v1.6.1/examples/features/vl3-basic
Then, I perform ping from nsc to other nsc or nse, and the network has a very high delay, which is significantly higher than in the example: https://github.com/networkservicemesh/deployments-k8s/tree/v1.6.1/examples/ Delay in pinging from nsc to nse in use-cases/Kernel2Wireguard2Kernel

vl3-basic Network latency data：
![image](https://github.com/networkservicemesh/deployments-k8s/assets/3714619/153de575-2049-42ac-8379-212908b5d10d)
Kernel2Wireguard2Kernel Network latency data：

**Comment by glazychev-art** [comment]
Is there any reason that you are using version v1.6.1? The fact is that we regularly update VPP version, which is mainly used by our applications. The problem may have already been fixed.
It would also be cool if you share your environment.

**Comment by glazychev-art** [comment]
Annotations - https://networkservicemesh.io/docs/concepts/k8s/#adding-network-services-to-a-pod
```
            annotations:
               networkservicemesh.io: kernel://kernel2wireguard2kernel/nsm-1xx
```
Annotations is used by NSM admission-webhook to add an NSC (NetworkService Client) sidecar to your application.
For example, if your pod has `annotations: networkservicemesh.io: kernel://kernel2wireguard2kernel/nsm-1xx`, admission-webhook adds a sidecar:
```
  cmd-nsc:
  ...
    Image:          ghcr.io/networkservicemesh/ci/cmd-nsc:02f77d4
  ...
    Environment:
      NSM_NETWORK_SERVICES:      kernel://kernel2wireguard2kernel/nsm-1xx
      ...
```
You can try [this example](https://github.com/networkservicemesh/deployments-k8s/tree/v1.6.1/examples/features/webhook) and take a look at the `kubectl describe pod ...` of `nettools`

**Comment by 316953425** [comment]
> Is there any reason that you are using version v1.6.1? The fact is that we regularly update VPP version, which is mainly used by our applications. The problem may have already been fixed. It would also be cool if you share your environment.

I will verify it in our latest version in the future. If there are still problems with high latency, I will share the environment. Thank you.

**Comment by 316953425** [comment]
> Is there any reason that you are using version v1.6.1? The fact is that we regularly update VPP version, which is mainly used by our applications. The problem may have already been fixed. It would also be cool if you share your environment.

hi glazychev-art
I will verify it in our latest version in the future. If there are still problems with high latency, I will share the environment. Thank you.

**Comment by 316953425** [comment]
> Annotations - https://networkservicemesh.io/docs/concepts/k8s/#adding-network-services-to-a-pod
> 
> ```
>             annotations:
>                networkservicemesh.io: kernel://kernel2wireguard2kernel/nsm-1xx
> ```
> 
> Annotations is used by NSM admission-webhook to add an NSC (NetworkService Client) sidecar to your application. For example, if your pod has `annotations: networkservicemesh.io: kernel://kernel2wireguard2kernel/nsm-1xx`, admission-webhook adds a sidecar:
> 
> ```
>   cmd-nsc:
>   ...
>     Image:          ghcr.io/networkservicemesh/ci/cmd-nsc:02f77d4
>   ...
>     Environment:
>       NSM_NETWORK_SERVICES:      kernel://kernel2wireguard2kernel/nsm-1xx
>       ...
> ```
> 
> You can try [this example](https://github.com/networkservicemesh/deployments-k8s/tree/v1.6.1/examples/features/webhook) and take a look at the `kubectl describe pod ...` of `nettools`
hi glazychev-art

What makes me a little confused is why in vl3-basic, our nsc does not use this format of yaml

```
---
apiVersion: v1
kind: Pod
metadata:
  name: alpine
  labels:
    app: alpine
  annotations:
    networkservicemesh.io: kernel://nse-composition/nsm-1?app=alpine
spec:
  containers:
  - name: alpine
    image: alpine:3.15.0
    imagePullPolicy: IfNotPresent
    stdin: true
    tty: true

  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - topologyKey: kubernetes.io/hostname
          labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - nse-kernel
```


 but uses this format of yaml

```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nsc-kernel
  labels:
    app: nsc-kernel
spec:
  selector:
    matchLabels:
      app: nsc-kernel
  template:
    metadata:
      labels:
        app: nsc-kernel
        "spiffe.io/spiffe-id": "true"
    spec:
      containers:
        - name: nsc
          #image: ghcr.io/networkservicemesh/cmd-nsc:v1.6.1
          image: myimg:0.1
          imagePullPolicy: IfNotPresent
          env:
            - name: SPIFFE_ENDPOINT_SOCKET
              value: unix:///run/spire/sockets/agent.sock
            - name: NSM_LOG_LEVEL
              value: TRACE
            - name: NSM_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          volumeMounts:
            - name: spire-agent-socket
              mountPath: /run/spire/sockets
              readOnly: true
            - name: nsm-socket
              mountPath: /var/lib/networkservicemesh
              readOnly: true
          resources:
            requests:
              #cpu: 100m
              memory: 40Mi
            limits:
              memory: 80Mi
              #cpu: 200m
      volumes:
        - name: spire-agent-socket
          hostPath:
            path: /run/spire/sockets
            type: Directory
        - name: nsm-socket
          hostPath:
            path: /var/lib/networkservicemesh
            type: DirectoryOrCreate

```
