### ISSUE TITLE
add hostNetwork: true  for alpine in Kernel2Ethernet2Kernel

### ISSUE THREAD

**Issue by 316953425** [networkservicemesh/deployments-k8s#10754]
hi @glazychev-art 

I deployed the Kernel2Ethernet2Kernel example, but modified the alpine configuration. The configuration is as follows. I don't know if nsm supports it, but it looks like it works.

```
---
apiVersion: v1
kind: Pod
metadata:
  name: alpine
  labels:
    app: alpine
  annotations:
    networkservicemesh.io: kernel://kernel2ethernet2kernel/nsm-1
spec:


  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet

  containers:
  - name: alpine
    image: alpine:3.15.0
    imagePullPolicy: IfNotPresent
    # simple `sleep` command would work
    # but we need `trap` to be able to delete pods quckly
    command: ["/bin/sh", "-c", "trap : TERM INT; sleep infinity & wait"]
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - topologyKey: kubernetes.io/hostname
          labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - nse-kernel
```

But if I add another client2 in kustomization.yaml and the client2.yaml configuration is the same as above, it doesn't seem to work.
Looking forward to your help, thank you very much

```
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ns-kernel2ethernet2kernel

resources:
- ns-kernel2ethernet2kernel.yaml
- client.yaml
- client2.yaml
- netsvc.yaml
- ../../../apps/nse-kernel

patchesStrategicMerge:
- patch-nse.yaml
```

**Comment by glazychev-art** [comment]
@316953425 
Have you tried to change the interface name for the second client from `nsm-1` to `nsm-2`?
```
  annotations:
    networkservicemesh.io: kernel://kernel2ethernet2kernel/nsm-2
```

**Comment by 316953425** [comment]
> @316953425 Have you tried to change the interface name for the second client from `nsm-1` to `nsm-2`?
> 
> ```
>   annotations:
>     networkservicemesh.io: kernel://kernel2ethernet2kernel/nsm-2
> ```

hi @glazychev-art 
yes
client and client2 have same ip 
<img width="710" alt="1702546170881" src="https://github.com/networkservicemesh/deployments-k8s/assets/3714619/b7db32d2-3b41-49e7-b72a-f16ea9b445cb">
<img width="680" alt="1702546205494" src="https://github.com/networkservicemesh/deployments-k8s/assets/3714619/f5f8a9d1-7df1-4bf4-b513-c1e55aecf0ac">
<img width="743" alt="1702546234850" src="https://github.com/networkservicemesh/deployments-k8s/assets/3714619/dd9d0f22-8090-4a9f-8820-6a0afa93d1e9">
<img width="514" alt="1702546251630" src="https://github.com/networkservicemesh/deployments-k8s/assets/3714619/a7e81000-275c-487f-af8d-72573427d0c2">

**Comment by glazychev-art** [comment]
@316953425 
As I can see you have both `nsm-1` and `nsm-2` for alpine and alpine-2. And they have different IP-addresses: 172.16.102.239 and 172.16.102.237.
You see both interfaces because alpine and alpine-2 are located in the same network namespace.

Please take a look at what the `hostNetwork` flag means in Kubernetes.

**Comment by 316953425** [comment]
> hostNetwork

hi @glazychev-art 
I'm new to k8s. I'm very sorry that I don't quite understand what you mean. Two pods in the same namespace cannot use hostNetwork: true at the same time. Is that true?

**Comment by glazychev-art** [comment]
In your example above you have both `nsm-1` and `nsm-2`:

![img1](https://github.com/networkservicemesh/deployments-k8s/assets/17748275/28f349b3-0910-4afb-8712-c99f66955144)

![img2](https://github.com/networkservicemesh/deployments-k8s/assets/17748275/a8bbf605-3281-4011-b3b3-a6f720cf7e21)

> Two pods in the same namespace cannot use hostNetwork: true at the same time. Is that true?

Kubernetes namespace and Linux network namespace are completely different things.
Please refer to the Kubernetes documentation to understand what `hostNetwork` option means.

**Comment by 316953425** [comment]
hi @glazychev-art 
my client.yaml have config like this :
```
  annotations:
    networkservicemesh.io: kernel://kernel2ethernet2kernel/nsm-1
spec:
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet

```
my client2.yaml have config like this :
  annotations:
    networkservicemesh.io: kernel://kernel2ethernet2kernel/nsm-2
spec:
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet

why in pod client and client2 both have nsm-1 and nsm-2

I read the hostNetwork document. I understand that hostNetwork maps the physical network directly to the pod. Is it because of hostNetwork?

>In your example above you have both nsm-1 and nsm-2:
