### ISSUE TITLE
Adding a new Network Services Endpoind to the running NSC 

### ISSUE THREAD

**Issue by nephilimboy** [networkservicemesh/deployments-k8s#10772]
Hi all,

Considering the NSM [multiple-services example](https://github.com/networkservicemesh/deployments-k8s/tree/main/examples/features/multiple-services), is there anyway to add a new end point service to the existing/running NSC (the NSC which already existed)?

Assume the below NSC's YAML file

```
---
apiVersion: v1
kind: Pod
metadata:
  name: alpine
  labels:
    app: alpine
  annotations:
    networkservicemesh.io: kernel://multiple-services-1/nsm-1,kernel://multiple-services-2/nsm-2
spec:
  containers:
  - name: alpine
    image: alpine:3.15.0
    imagePullPolicy: IfNotPresent
    # simple `sleep` command would work
    # but we need `trap` to be able to delete pods quckly
    command: ["/bin/sh", "-c", "trap : TERM INT; sleep infinity & wait"]
```

Is there anyway to change and then apply the annotations part in the Yaml and add the 3rd Network Services Endpoind like below while the NSC pod is running? In my use case I am not allowed to recreate the NSC pods. 

 ```
annotations:
    networkservicemesh.io: kernel://multiple-services-1/nsm-1,kernel://multiple-services-2/nsm-2,kernel://multiple-services-3/nsm-3
```
I appreciate any suggestions or workaround about this matter.
