### ISSUE TITLE
Help about nsm

### ISSUE THREAD

**Issue by 316953425** [networkservicemesh/deployments-k8s#11447]
hi @glazychev-art and other developers
I found a document on Google (https://docs.google.com/presentation/d/1IC2kLnQGDz1hbeO0rD7Y82O_4NwzgIoGgm0oOXyaQ9Y/edit?pli=1#slide=id.g4042dbe7c0_11_698) about nsm

Pages 80 to 127 of this document introduce how nsm allows pods to directly use the physical network card on the node.

The configuration about nsm in this doc like this

```
kind: NetworkService
apiVersion: V1
metadata:  
    name: enhanced-corp-connectivity
spec:
    payload: IP

```

```
apiVersion: v1
kind: Pod
metadata:
  name: hannahs-pod
spec:
  containers:
  - name: hannahs-container
    image: hannahsimage
    resources:
      requests:
        cpu: 2
        networkservicemesh.io/enhanced-corp-connectivity: 1
      limits:
        networkservicemesh.io/enhanced-corp-connectivity: 1
```

I'm a little  confused about whether this is correct. I feel like it shouldn't be possible to let the pod directly use the physical network card on the node.

error msg
<img width="750" alt="1711077094200" src="https://github.com/networkservicemesh/deployments-k8s/assets/3714619/8a50c5f3-7145-4789-9767-dfff7b895a3d">
<img width="760" alt="1711077114507" src="https://github.com/networkservicemesh/deployments-k8s/assets/3714619/701f1a0a-85ef-46e3-b3ad-24c05d07e05e">

my nsm version：v1.11.1
Could you take a look at it for me? Thank you very much for your reply.
