### ISSUE TITLE
nse interface incorrect name

### ISSUE THREAD

**Issue by p4lik4ri** [networkservicemesh/deployments-k8s#12028]
## Question

I add annotations to my Clients for example:

```
pod1:
  networkservicemesh.io: kernel://kernel2ethernet2kernel/nsm-1

pod2:
  networkservicemesh.io: kernel://kernel2ethernet2kernel/nsm-2
```

When i exec in each pod can see the interaces with the name i gave them:
pod1:
![nsc-1](https://github.com/networkservicemesh/deployments-k8s/assets/94470659/4315fc2a-d280-4c4d-87bb-f927e16dbe7c)
pod2:
![nsc-2](https://github.com/networkservicemesh/deployments-k8s/assets/94470659/3d8ddccf-e32d-453a-94fa-ed66c0f8b976)

But in the NSE pod the interfaces are illustrated with weird characters, is this a Bug?
How i should know which NSE interface correspond to each NSC ?

![NSE](https://github.com/networkservicemesh/deployments-k8s/assets/94470659/70133220-1f4c-405c-9e1b-5efdd59813d0)

* Kubernetes Version: kind

thanks
