### ISSUE TITLE
Spire Server not listen the 8443 port by default

### ISSUE THREAD

**Issue by anselmobattisti** [networkservicemesh/deployments-k8s#12543]
## Question

After installing the spire using the tutorial 

https://github.com/networkservicemesh/deployments-k8s/tree/main/examples/interdomain/three_cluster_configuration/spiffe_federation

it should be possible to access the spire server in the port 8443. however it not working.

For some reason, the file https://github.com/networkservicemesh/deployments-k8s/blob/main/examples/spire/base/server-statefulset.yaml is only opening the port 8081

```yaml
          ports:
            - containerPort: 8081
```

however in the file https://github.com/networkservicemesh/deployments-k8s/blob/main/examples/spire/cluster1/server.conf the bundle_endpoint_url requeires the port 8443

the endpoint 

```sh
            bundle_endpoint_url = "https://spire-server.spire.my.cluster2:8443"
```

To solve this problem i need to manually add the port 8443 to the service spire-server using a patch

```yaml
---
apiVersion: v1
kind: Service
metadata:
  name: spire-server
  namespace: spire
  annotations:
    metallb.universe.tf/address-pool: my-ip-pool
spec:
  type: LoadBalancer
  selector:
    app: spire-server
  ports:
    - name: spire-server
      port: 8081
      targetPort: 8081
      protocol: TCP
    - name: bundle-endpoint
      port: 8443
      targetPort: 8443
      protocol: TCP
```

How about to include this soluction in this example?

## Examples

In a pod inside cluster1 after execute

```shell
nc -vz spire-server.spire.my.cluster2 8443
```
it fails

## Context

```sh
=================
CREATING CLUSTERS
=================
Creating cluster "cluster1" ...
 ✓ Ensuring node image (kindest/node:v1.31.2) 🖼
 ✓ Preparing nodes 📦 📦  
 ✓ Writing configuration 📜 
 ✓ Starting control-plane 🕹️ 
 ✓ Installing CNI 🔌 
 ✓ Installing StorageClass 💾 
 ✓ Joining worker nodes 🚜 
Set kubectl context to "kind-cluster1"
You can now use your cluster with:

kubectl cluster-info --context kind-cluster1

Have a nice day! 👋
+==============================+
| Cluster cluster1 is ready :) |
+==============================+
Creating cluster "cluster2" ...
 ✓ Ensuring node image (kindest/node:v1.31.2) 🖼
 ✓ Preparing nodes 📦 📦  
 ✓ Writing configuration 📜 
 ✓ Starting control-plane 🕹️ 
 ✓ Installing CNI 🔌 
 ✓ Installing StorageClass 💾 
 ✓ Joining worker nodes 🚜 
Set kubectl context to "kind-cluster2"
You can now use your cluster with:

kubectl cluster-info --context kind-cluster2

Thanks for using kind! 😊
+==============================+
| Cluster cluster2 is ready :) |
+==============================+
Creating cluster "cluster3" ...
 ✓ Ensuring node image (kindest/node:v1.31.2) 🖼
 ✓ Preparing nodes 📦 📦  
 ✓ Writing configuration 📜 
 ✓ Starting control-plane 🕹️ 
 ✓ Installing CNI 🔌 
 ✓ Installing StorageClass 💾 
 ✓ Joining worker nodes 🚜 
Set kubectl context to "kind-cluster3"
You can now use your cluster with:

kubectl cluster-info --context kind-cluster3

Have a question, bug, or feature request? Let us know! https://kind.sigs.k8s.io/#community 🙂
+==============================+
| Cluster cluster3 is ready :) |
+==============================+
```

## Other artifacts/Logs

Logs file from ``kubectl cluster-info dump``:
