### ISSUE TITLE
Use nodeName instead of kubernetes.io/hostname label

### ISSUE THREAD

**Issue by d-uzlov** [networkservicemesh/deployments-k8s#1261]
## Overview

Currently this repository uses `spec.nodeSelector[kubernetes.io/hostname]` label for defining node affinity.
This label is equivalent to `spec.nodeName`, unless the label was deliberately changed.
Using `spec.nodeName` field for node affinity would be simpler.

## Example:
Replace this:
```yaml
spec:
  nodeSelector:
    kubernetes.io/hostname: ${NODES[0]}
```
with this:
```yaml
spec:
  nodeName: ${NODES[0]}
```
