### ISSUE TITLE
Delay pod start until spire-server is reachable

### ISSUE THREAD

**Issue by richardstone** [networkservicemesh/deployments-k8s#4467]
To avoid unexpected restart of any NSM pod, it would be great if there would be a check at the start of every NSM pod, wether the spire-server is already available and can handle requests. 

I'm thinkg of a simple check like this at the start:
`until nc -w 2 -vz spire-server 8081; do sleep 2; done`

Would be nice if the wait and sleep time could be configured.

**Comment by edwarnicke** [comment]
I like this idea a lot :)

@richardstone what was the other thing around probes you found?

**Comment by richardstone** [comment]
@edwarnicke 

It was about the readiness probe settings of the pods. This is what works for us:
      failureThreshold: 200
      initialDelaySeconds: 1
      periodSeconds: 1
      successThreshold: 1
      timeoutSeconds: 2
      
These are rough numbers for now. initialDelaySeconds and failureTreshold will definitely change in the future.

**Comment by edwarnicke** [comment]
@richardstone Keep us updated :)

**Comment by szvincze** [comment]
@edwarnicke Do you think that such check that @richardstone proposed can be implemented?

**Comment by edwarnicke** [comment]
@denis-tingaikin Does @NikitaSkrynnik  have bandwidth for this?

**Comment by denis-tingaikin** [comment]
>@denis-tingaikin Does @NikitaSkrynnik have bandwidth for this?

@edwarnicke No, we don't work with this issue yet.

 From my view this looks interesting to apply. PRs are welcome!

**Comment by denis-tingaikin** [comment]
@richardstone , @szvincze be free to open PR. We'll consider it ASAP.

**Comment by edwarnicke** [comment]
@szvincze @richardstone @LionelJouin Could you add the the new parameters you are suggesting including the startup time?  I think we are good with dropping 1.17... but need the correct parameter values.

**Comment by szvincze** [comment]
@edwarnicke We are working on it but need some time for refinement and proper test.

**Comment by edwarnicke** [comment]
@szvincze Do you have an ETA?  I'd love to get it out with the v1.3 release :)

**Comment by richardstone** [comment]
@edwarnicke I'd say early next week.

**Comment by richardstone** [comment]
Hi @edwarnicke!

I have managed to finetune the probes. Executed many upgrade tests, and it seems that - due to the randomness in picking the components during the process - upgrade-time is around 50-80 sec which is not bad compared to the times before (it was around 60sec). In some cases the upgrade takes a bit more time than before, but now I have barely seen any restart of NSM pods.

Changes I have made:
- startupProbe introduced in forwarder and nsmgr (both using the same grpc probe as for the liveness and readiness probes)
- finetuned liveness and readiness probe times 

Probes timing now look like this (startupProbe where applicable):
```
    livenessProbe:
      failureThreshold: 25
      initialDelaySeconds: 10
      periodSeconds: 5
      timeoutSeconds: 2
    readinessProbe:
      failureThreshold: 120
      initialDelaySeconds: 1
      periodSeconds: 1
      successThreshold: 1
      timeoutSeconds: 2
    startupProbe:
      failureThreshold: 25
      periodSeconds: 5
```
