### ISSUE TITLE
NSC - Add support for K8S PSS restricted/baseline profiles (for hostPath volumes)

### ISSUE THREAD

**Issue by pnavali** [networkservicemesh/deployments-k8s#9218]
## Overview
K8S 1.25 release deprecates PSP (Pod security policy) and enables PSS (Pod Security Standards)/PSA (Pod Security Admission controller) by default. The PSS has 3 profiles - Privileged, Baseline and Restricted. 
NSC requires hostPath volumes for unix sockets. HostPath volumes are not permitted in Baseline/Restricted profiles. 

Need a solution for NSC to work in Baseline/Restricted profiles.

Couple of options:
- NSM CSI driver : Add a NSM CSI driver plugin to mount the hostPath volume.
- Use network sockets instead of unix sockets and eliminate the need for hostPath volume.

## References

https://kubernetes.io/docs/concepts/security/pod-security-standards/

**Comment by denis-tingaikin** [comment]
Decomposition:

- Implement NSM CSI driver ~ 14h
- Test NSM CSI driver (nsmgr sidecar/pod)  ~ 7h
- Test NSM CSI driver  + NSM infra ~ 7h
- Add NSM CSI driver yaml deployment ~ 4h
- Include Feature into new example ~7h
- Pass tests ~7h
- Pass review ~3h

TOTAL: 49h

**Comment by glazychev-art** [comment]
To use CSI, we need to change the volumes type from `hostPath` to `csi` on NSC and NSE. 
For example:
```
      volumes:
        - name: nsm-socket
          hostPath:
            path: /var/lib/networkservicemesh
            type: DirectoryOrCreate
```
becomes
```
      volumes:
        - name: nsm-socket
          csi:
            driver: "csi.networkservicemesh.io"
            readOnly: true
```

To test NSM-CSI on CI, we will need to modify our examples.

**We have 2 options:**
1. Get rid of the use of hostPath in all our examples in favor of CSI
2. Continue using hostPath, but create duplicate tests for CSI examples
